# coding: utf-8
"""Client-side private config.

Generated by `bigqmt-init`.
DO NOT COMMIT: this file holds an account id and Redis credentials.
"""

BIGQMT_ACCOUNT_ID = '8890809055'
BIGQMT_RPC_TIMEOUT_SECONDS = 30.0

BIGQMT_REDIS_CONFIG = {
    "transport": 'zmq',
    "host": '127.0.0.1',
    "port": 15563,
    "db": 5,
    "username": '',
    "password": '568815',
    # The QMT-side server derives this port from the account id. Set it
    # explicitly to skip service discovery; change it if the server logs
    # a different bind port.
    # 2026-09-09: 服务端已配置真实账号 8890809055 -> 绑定 15560+55=15615, 客户端改回 15615.
    "zmq": {"connect_address": "tcp://127.0.0.1:15615"},
}

# Reference/history reads go straight to Big QMT's FormulaServer (port
# 58600) instead of over RPC. Every miss falls back to RPC, so an
# unreachable 58600 changes nothing.
BIGQMT_FORMULA_SERVER_CONFIG = {
    "enabled": True,
}

BIGQMT_LOCAL_CACHE_CONFIG = {
    "enabled": True,
    "dir": None,
    "fallback_rpc": False,
    "format": "auto",
}
